In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_a3fd32fbc881465dbc687e2712245abb = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='BkYJRa0AG65HHKgDkCgwpPaZeSN9tRODnHWWhuJRtsR8',
    ibm_auth_endpoint="https://iam.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')

body = client_a3fd32fbc881465dbc687e2712245abb.get_object(Bucket='myproject-donotdelete-pr-ccoqyx76bdreat',Key='finaldata123.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df1 = pd.read_csv(body)
df1.head()



may    june   july  temperature  label
0  100.0  177.90  177.9         24.0  19.00
1   90.0  118.60   59.3         21.0  12.00
2   82.0   89.61   84.0         23.0  11.00
3   95.0   98.00   92.0         21.0  13.57
4   76.0   74.00   68.0         20.0  10.90

In [4]:
df=df1.head(10)
df

may    june    july  temperature  label
0  100.00  177.90  177.90         24.0  19.00
1   90.00  118.60   59.30         21.0  12.00
2   82.00   89.61   84.00         23.0  11.00
3   95.00   98.00   92.00         21.0  13.57
4   76.00   74.00   68.00         20.0  10.90
5   16.62   16.62   11.08         27.0   1.64
6  120.90   77.73   77.73         30.0   9.21
7   51.82   51.82   25.91         24.0   5.32
8   36.27   36.27   24.18         24.0   4.03
9   19.50   56.52   56.52         25.0   5.30

In [5]:
df.corr()

may      june      july  temperature     label
may          1.000000  0.724374  0.673175    -0.080103  0.797631
june         0.724374  1.000000  0.923074    -0.310466  0.962852
july         0.673175  0.923074  1.000000    -0.145784  0.926737
temperature -0.080103 -0.310466 -0.145784     1.000000 -0.403706
label        0.797631  0.962852  0.926737    -0.403706  1.000000

In [6]:
df.isnull().any()

may            False
june           False
july           False
temperature    False
label          False
dtype: bool

In [7]:
x = df.iloc[:,0:4].values
y = df.iloc[:,4].values
y

array([ 19.  ,  12.  ,  11.  ,  13.57,  10.9 ,   1.64,   9.21,   5.32,
         4.03,   5.3 ])

In [8]:
x

array([[ 100.  ,  177.9 ,  177.9 ,   24.  ],
       [  90.  ,  118.6 ,   59.3 ,   21.  ],
       [  82.  ,   89.61,   84.  ,   23.  ],
       [  95.  ,   98.  ,   92.  ,   21.  ],
       [  76.  ,   74.  ,   68.  ,   20.  ],
       [  16.62,   16.62,   11.08,   27.  ],
       [ 120.9 ,   77.73,   77.73,   30.  ],
       [  51.82,   51.82,   25.91,   24.  ],
       [  36.27,   36.27,   24.18,   24.  ],
       [  19.5 ,   56.52,   56.52,   25.  ]])

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.3,random_state = 0)

In [10]:
from sklearn.linear_model import LinearRegression
mlr=LinearRegression()

In [11]:
mlr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [12]:
y_pred=mlr.predict(x_test)
y_pred

array([ 11.40228095,   4.51842283,  11.24484437])

In [13]:
mlr.intercept_

11.519519013321032

In [14]:
mlr.coef_

array([ 0.04174635,  0.02285061,  0.05534687, -0.44509646])

In [15]:
from sklearn.metrics import r2_score

In [16]:
r2_score(y_test,y_pred)

0.98373578499793224

In [17]:
!pip install watson-machine-learning-client --upgrade

Requirement already up-to-date: watson-machine-learning-client in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (1.0.365)
Requirement not upgraded as not directly required: certifi in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from watson-machine-learning-client) (2019.3.9)
Requirement not upgraded as not directly required: tqdm in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from watson-machine-learning-client) (4.19.5)
Requirement not upgraded as not directly required: requests in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from watson-machine-learning-client) (2.18.4)
Requirement not upgraded as not directly required: urllib3 in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from watson-machine-learning-client) (1.22)
Requirement not upgraded as not directly required: ibm-cos-sdk in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from watson-machine-learning-client) (2.0.1)
Requirement not upgraded as not dire

In [18]:
from watson_machine_learning_client import WatsonMachineLearningAPIClient


/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
2019-05-23 08:49:55,275 - watson_machine_learning_client.metanames - WARNING - 'AUTHOR_EMAIL' meta prop is deprecated. It will be ignored.


In [19]:
wml_credentials={
  "username": "2a4d977c-f485-428b-8b65-79a75e4697a6",
  "password": "26d97a1a-6069-493e-a3ab-1936dc773358",
  "instance_id": "fe4de994-99fd-49f7-9f51-027261fa3b7a",
  "url": "https://eu-gb.ml.cloud.ibm.com",
}

In [20]:
client = WatsonMachineLearningAPIClient( wml_credentials )

In [21]:
metadata = {
    client.repository.ModelMetaNames.AUTHOR_NAME: "NAGA BABU GOLI",
    client.repository.ModelMetaNames.AUTHOR_EMAIL: "nagraghu971@gmail.com",
    client.repository.ModelMetaNames.NAME:"mlRMODEL"
}

In [22]:
model= client.repository.store_model( mlr, meta_props=metadata )

In [23]:
client.repository.list_models()

------------------------------------  -----------  ------------------------  -----------------
GUID                                  NAME         CREATED                   FRAMEWORK
20f0067f-d3dd-44e4-b0be-ae6103a5ba24  mlRMODEL     2019-05-23T08:49:55.478Z  scikit-learn-0.19
60645d4a-9a12-45d1-ae29-a72e76a9b6da  mlRMODEL     2019-05-22T19:37:10.292Z  scikit-learn-0.19
5b5b7398-6d04-417c-ba35-276d02c962de  keras model  2019-05-18T06:46:40.700Z  tensorflow-1.5
65dfef66-f3e8-454e-99fa-d0c07601bb32  Crazy-model  2019-05-18T05:14:48.935Z  wml-1.2
c966372e-25d6-4d4b-8f64-526a7728f8e1  MLR model;   2019-05-14T08:34:10.277Z  scikit-learn-0.19
------------------------------------  -----------  ------------------------  -----------------


In [24]:
published_model_uid=client.repository.get_model_uid(model)

In [25]:
published_model_uid

'20f0067f-d3dd-44e4-b0be-ae6103a5ba24'

In [26]:
deployment=client.deployments.create(published_model_uid,name="mlRMODEL")



#######################################################################################

Synchronous deployment creation for uid: '20f0067f-d3dd-44e4-b0be-ae6103a5ba24' started

#######################################################################################


INITIALIZING
DEPLOY_SUCCESS


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='9da9e833-f882-4daa-8c56-63989058aadf'
------------------------------------------------------------------------------------------------




In [27]:
scoring_endpoint=client.deployments.get_scoring_url(deployment)

In [28]:
scoring_endpoint

'https://eu-gb.ml.cloud.ibm.com/v3/wml_instances/fe4de994-99fd-49f7-9f51-027261fa3b7a/deployments/9da9e833-f882-4daa-8c56-63989058aadf/online'